name: 'react-frontend'

services:
  reactapp:
    build:
      args:
        USER_ID: ${USER_ID:-0}
        GROUP_ID: ${GROUP_ID:-0}
        USER_NAME: ${USER_NAME:-0}
        GROUP_NAME: ${GROUP_NAME:-0}
      context: .
      dockerfile: Dockerfile
    container_name: react-frontend
    volumes:
      - .:/app
    command: sh -c 'npm install && npm start'
    ports:
      - 3000:3000
    networks:
      - network

networks:
  network:
    driver: bridge
    name: ${COMPOSE_PROJECT_NAME:-network}